### ISSUE TITLE
BlobTrack1.py error on raspberry pi 2

### ISSUE THREAD

**Issue by Antoniodv** [jbeale1/OpenCV#1]
When I try to run BlobTrack1.py on my raspberry2 i got this error:

OpenCV: FFMPEG: tag 0xffffffff/'????' is not found (format 'avi / AVI (Audio Video Interleaved)')'
bnum, x, y, rad, vel, dist

Plese, could you tell me how to solve?
Thanks

**Comment by jbeale1** [comment]
Hello,

I assume you're using this code:  https://github.com/jbeale1/OpenCV/blob/master/BlobTrack1.py
I have only tried the code with .mp4 files created from the Raspberry Pi camera (.h246, then MP4Box to .mp4).
My code contained the line:

  cap = cv2.VideoCapture('2015-06-28-CarTest.mp4')  # compilation of test cases

and I assume you edited that line to point to whatever video file you have, that you want to process.  (If you did not 
edit that line, there will be an error due to that file not existing on your Pi.)

If you're trying it with an .avi file, I don't know what may happen.  AVI is not a codec, it is a file "wrapper format" that 
might contain any kind of video codec and from your error message, FFMPEG on the Pi does not like whatever file you 
are sending it.

regards
John
